version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies.
      - npm i

  build:
    commands:
      - echo Build started
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: './dist/rimss*'
  discard-paths: no
